/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedForbiddenRouteImport } from "./routes/_authenticated.forbidden";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated.dashboard";
import { Route as AuthenticatedDevUiKitRouteImport } from "./routes/_authenticated.dev.ui-kit";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDevUiKitRoute = AuthenticatedDevUiKitRouteImport.update({
  id: "/dev/ui-kit",
  path: "/dev/ui-kit",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute;
  "/_authenticated/forbidden": typeof AuthenticatedForbiddenRoute;
  "/_authenticated/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/forbidden" | "/dev/ui-kit";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/forbidden" | "/dev/ui-kit";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_authenticated/dashboard"
    | "/_authenticated/forbidden"
    | "/_authenticated/dev/ui-kit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/forbidden": {
      id: "/_authenticated/forbidden";
      path: "/forbidden";
      fullPath: "/forbidden";
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dev/ui-kit": {
      id: "/_authenticated/dev/ui-kit";
      path: "/dev/ui-kit";
      fullPath: "/dev/ui-kit";
      preLoaderRoute: typeof AuthenticatedDevUiKitRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute;
  AuthenticatedDevUiKitRoute: typeof AuthenticatedDevUiKitRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedDevUiKitRoute: AuthenticatedDevUiKitRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
