/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedWorkOrdersRouteImport } from "./routes/_authenticated.work-orders";
import { Route as AuthenticatedTraceabilityRouteImport } from "./routes/_authenticated.traceability";
import { Route as AuthenticatedGuideRouteImport } from "./routes/_authenticated.guide";
import { Route as AuthenticatedForbiddenRouteImport } from "./routes/_authenticated.forbidden";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated.dashboard";
import { Route as AuthenticatedAuditEventsRouteImport } from "./routes/_authenticated.audit-events";
import { Route as AuthenticatedWorkOrdersNewRouteImport } from "./routes/_authenticated.work-orders_.new";
import { Route as AuthenticatedWorkOrdersWorkOrderIdRouteImport } from "./routes/_authenticated.work-orders_.$workOrderId";
import { Route as AuthenticatedTraceabilityTraceNodeIdRouteImport } from "./routes/_authenticated.traceability_.$traceNodeId";
import { Route as AuthenticatedQualityInspectionsRouteImport } from "./routes/_authenticated.quality.inspections";
import { Route as AuthenticatedQualityIncidentsRouteImport } from "./routes/_authenticated.quality.incidents";
import { Route as AuthenticatedMaterialsLotsRouteImport } from "./routes/_authenticated.materials.lots";
import { Route as AuthenticatedMaterialsBomsRouteImport } from "./routes/_authenticated.materials.boms";
import { Route as AuthenticatedExecutionQueueRouteImport } from "./routes/_authenticated.execution.queue";
import { Route as AuthenticatedDevUiKitRouteImport } from "./routes/_authenticated.dev.ui-kit";
import { Route as AuthenticatedAdminUsersRouteImport } from "./routes/_authenticated.admin.users";
import { Route as AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRouteImport } from "./routes/_authenticated.work-orders_.$workOrderId.material-reservations";
import { Route as AuthenticatedQualityInspectionsInspectionIdRouteImport } from "./routes/_authenticated.quality.inspections_.$inspectionId";
import { Route as AuthenticatedQualityIncidentsQualityIncidentIdRouteImport } from "./routes/_authenticated.quality.incidents_.$qualityIncidentId";
import { Route as AuthenticatedMaterialsLotsMaterialLotIdRouteImport } from "./routes/_authenticated.materials.lots_.$materialLotId";
import { Route as AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRouteImport } from "./routes/_authenticated.execution.lots_.$productionLotId.steps_.$processStepRevisionId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: "/work-orders",
  path: "/work-orders",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: "/traceability",
    path: "/traceability",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: "/guide",
  path: "/guide",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAuditEventsRoute =
  AuthenticatedAuditEventsRouteImport.update({
    id: "/audit-events",
    path: "/audit-events",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedWorkOrdersNewRoute =
  AuthenticatedWorkOrdersNewRouteImport.update({
    id: "/work-orders_/new",
    path: "/work-orders/new",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedWorkOrdersWorkOrderIdRoute =
  AuthenticatedWorkOrdersWorkOrderIdRouteImport.update({
    id: "/work-orders_/$workOrderId",
    path: "/work-orders/$workOrderId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedTraceabilityTraceNodeIdRoute =
  AuthenticatedTraceabilityTraceNodeIdRouteImport.update({
    id: "/traceability_/$traceNodeId",
    path: "/traceability/$traceNodeId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedQualityInspectionsRoute =
  AuthenticatedQualityInspectionsRouteImport.update({
    id: "/quality/inspections",
    path: "/quality/inspections",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedQualityIncidentsRoute =
  AuthenticatedQualityIncidentsRouteImport.update({
    id: "/quality/incidents",
    path: "/quality/incidents",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedMaterialsLotsRoute =
  AuthenticatedMaterialsLotsRouteImport.update({
    id: "/materials/lots",
    path: "/materials/lots",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedMaterialsBomsRoute =
  AuthenticatedMaterialsBomsRouteImport.update({
    id: "/materials/boms",
    path: "/materials/boms",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedExecutionQueueRoute =
  AuthenticatedExecutionQueueRouteImport.update({
    id: "/execution/queue",
    path: "/execution/queue",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedDevUiKitRoute = AuthenticatedDevUiKitRouteImport.update({
  id: "/dev/ui-kit",
  path: "/dev/ui-kit",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute =
  AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRouteImport.update({
    id: "/material-reservations",
    path: "/material-reservations",
    getParentRoute: () => AuthenticatedWorkOrdersWorkOrderIdRoute,
  } as any);
const AuthenticatedQualityInspectionsInspectionIdRoute =
  AuthenticatedQualityInspectionsInspectionIdRouteImport.update({
    id: "/quality/inspections_/$inspectionId",
    path: "/quality/inspections/$inspectionId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedQualityIncidentsQualityIncidentIdRoute =
  AuthenticatedQualityIncidentsQualityIncidentIdRouteImport.update({
    id: "/quality/incidents_/$qualityIncidentId",
    path: "/quality/incidents/$qualityIncidentId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedMaterialsLotsMaterialLotIdRoute =
  AuthenticatedMaterialsLotsMaterialLotIdRouteImport.update({
    id: "/materials/lots_/$materialLotId",
    path: "/materials/lots/$materialLotId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute =
  AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRouteImport.update(
    {
      id: "/execution/lots_/$productionLotId/steps_/$processStepRevisionId",
      path: "/execution/lots/$productionLotId/steps/$processStepRevisionId",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/guide": typeof AuthenticatedGuideRoute;
  "/traceability": typeof AuthenticatedTraceabilityRoute;
  "/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/materials/boms": typeof AuthenticatedMaterialsBomsRoute;
  "/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/quality/incidents": typeof AuthenticatedQualityIncidentsRoute;
  "/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/traceability/$traceNodeId": typeof AuthenticatedTraceabilityTraceNodeIdRoute;
  "/work-orders/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren;
  "/work-orders/new": typeof AuthenticatedWorkOrdersNewRoute;
  "/materials/lots/$materialLotId": typeof AuthenticatedMaterialsLotsMaterialLotIdRoute;
  "/quality/incidents/$qualityIncidentId": typeof AuthenticatedQualityIncidentsQualityIncidentIdRoute;
  "/quality/inspections/$inspectionId": typeof AuthenticatedQualityInspectionsInspectionIdRoute;
  "/work-orders/$workOrderId/material-reservations": typeof AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute;
  "/execution/lots/$productionLotId/steps/$processStepRevisionId": typeof AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/guide": typeof AuthenticatedGuideRoute;
  "/traceability": typeof AuthenticatedTraceabilityRoute;
  "/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/materials/boms": typeof AuthenticatedMaterialsBomsRoute;
  "/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/quality/incidents": typeof AuthenticatedQualityIncidentsRoute;
  "/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/traceability/$traceNodeId": typeof AuthenticatedTraceabilityTraceNodeIdRoute;
  "/work-orders/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren;
  "/work-orders/new": typeof AuthenticatedWorkOrdersNewRoute;
  "/materials/lots/$materialLotId": typeof AuthenticatedMaterialsLotsMaterialLotIdRoute;
  "/quality/incidents/$qualityIncidentId": typeof AuthenticatedQualityIncidentsQualityIncidentIdRoute;
  "/quality/inspections/$inspectionId": typeof AuthenticatedQualityInspectionsInspectionIdRoute;
  "/work-orders/$workOrderId/material-reservations": typeof AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute;
  "/execution/lots/$productionLotId/steps/$processStepRevisionId": typeof AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute;
  "/_authenticated/forbidden": typeof AuthenticatedForbiddenRoute;
  "/_authenticated/guide": typeof AuthenticatedGuideRoute;
  "/_authenticated/traceability": typeof AuthenticatedTraceabilityRoute;
  "/_authenticated/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/_authenticated/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/_authenticated/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/_authenticated/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/_authenticated/materials/boms": typeof AuthenticatedMaterialsBomsRoute;
  "/_authenticated/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/_authenticated/quality/incidents": typeof AuthenticatedQualityIncidentsRoute;
  "/_authenticated/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/_authenticated/traceability_/$traceNodeId": typeof AuthenticatedTraceabilityTraceNodeIdRoute;
  "/_authenticated/work-orders_/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren;
  "/_authenticated/work-orders_/new": typeof AuthenticatedWorkOrdersNewRoute;
  "/_authenticated/materials/lots_/$materialLotId": typeof AuthenticatedMaterialsLotsMaterialLotIdRoute;
  "/_authenticated/quality/incidents_/$qualityIncidentId": typeof AuthenticatedQualityIncidentsQualityIncidentIdRoute;
  "/_authenticated/quality/inspections_/$inspectionId": typeof AuthenticatedQualityInspectionsInspectionIdRoute;
  "/_authenticated/work-orders_/$workOrderId/material-reservations": typeof AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute;
  "/_authenticated/execution/lots_/$productionLotId/steps_/$processStepRevisionId": typeof AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/audit-events"
    | "/dashboard"
    | "/forbidden"
    | "/guide"
    | "/traceability"
    | "/work-orders"
    | "/admin/users"
    | "/dev/ui-kit"
    | "/execution/queue"
    | "/materials/boms"
    | "/materials/lots"
    | "/quality/incidents"
    | "/quality/inspections"
    | "/traceability/$traceNodeId"
    | "/work-orders/$workOrderId"
    | "/work-orders/new"
    | "/materials/lots/$materialLotId"
    | "/quality/incidents/$qualityIncidentId"
    | "/quality/inspections/$inspectionId"
    | "/work-orders/$workOrderId/material-reservations"
    | "/execution/lots/$productionLotId/steps/$processStepRevisionId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/audit-events"
    | "/dashboard"
    | "/forbidden"
    | "/guide"
    | "/traceability"
    | "/work-orders"
    | "/admin/users"
    | "/dev/ui-kit"
    | "/execution/queue"
    | "/materials/boms"
    | "/materials/lots"
    | "/quality/incidents"
    | "/quality/inspections"
    | "/traceability/$traceNodeId"
    | "/work-orders/$workOrderId"
    | "/work-orders/new"
    | "/materials/lots/$materialLotId"
    | "/quality/incidents/$qualityIncidentId"
    | "/quality/inspections/$inspectionId"
    | "/work-orders/$workOrderId/material-reservations"
    | "/execution/lots/$productionLotId/steps/$processStepRevisionId";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/audit-events"
    | "/_authenticated/dashboard"
    | "/_authenticated/forbidden"
    | "/_authenticated/guide"
    | "/_authenticated/traceability"
    | "/_authenticated/work-orders"
    | "/_authenticated/admin/users"
    | "/_authenticated/dev/ui-kit"
    | "/_authenticated/execution/queue"
    | "/_authenticated/materials/boms"
    | "/_authenticated/materials/lots"
    | "/_authenticated/quality/incidents"
    | "/_authenticated/quality/inspections"
    | "/_authenticated/traceability_/$traceNodeId"
    | "/_authenticated/work-orders_/$workOrderId"
    | "/_authenticated/work-orders_/new"
    | "/_authenticated/materials/lots_/$materialLotId"
    | "/_authenticated/quality/incidents_/$qualityIncidentId"
    | "/_authenticated/quality/inspections_/$inspectionId"
    | "/_authenticated/work-orders_/$workOrderId/material-reservations"
    | "/_authenticated/execution/lots_/$productionLotId/steps_/$processStepRevisionId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/work-orders": {
      id: "/_authenticated/work-orders";
      path: "/work-orders";
      fullPath: "/work-orders";
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/traceability": {
      id: "/_authenticated/traceability";
      path: "/traceability";
      fullPath: "/traceability";
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/guide": {
      id: "/_authenticated/guide";
      path: "/guide";
      fullPath: "/guide";
      preLoaderRoute: typeof AuthenticatedGuideRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/forbidden": {
      id: "/_authenticated/forbidden";
      path: "/forbidden";
      fullPath: "/forbidden";
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/audit-events": {
      id: "/_authenticated/audit-events";
      path: "/audit-events";
      fullPath: "/audit-events";
      preLoaderRoute: typeof AuthenticatedAuditEventsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/work-orders_/new": {
      id: "/_authenticated/work-orders_/new";
      path: "/work-orders/new";
      fullPath: "/work-orders/new";
      preLoaderRoute: typeof AuthenticatedWorkOrdersNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/work-orders_/$workOrderId": {
      id: "/_authenticated/work-orders_/$workOrderId";
      path: "/work-orders/$workOrderId";
      fullPath: "/work-orders/$workOrderId";
      preLoaderRoute: typeof AuthenticatedWorkOrdersWorkOrderIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/traceability_/$traceNodeId": {
      id: "/_authenticated/traceability_/$traceNodeId";
      path: "/traceability/$traceNodeId";
      fullPath: "/traceability/$traceNodeId";
      preLoaderRoute: typeof AuthenticatedTraceabilityTraceNodeIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/quality/inspections": {
      id: "/_authenticated/quality/inspections";
      path: "/quality/inspections";
      fullPath: "/quality/inspections";
      preLoaderRoute: typeof AuthenticatedQualityInspectionsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/quality/incidents": {
      id: "/_authenticated/quality/incidents";
      path: "/quality/incidents";
      fullPath: "/quality/incidents";
      preLoaderRoute: typeof AuthenticatedQualityIncidentsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/materials/lots": {
      id: "/_authenticated/materials/lots";
      path: "/materials/lots";
      fullPath: "/materials/lots";
      preLoaderRoute: typeof AuthenticatedMaterialsLotsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/materials/boms": {
      id: "/_authenticated/materials/boms";
      path: "/materials/boms";
      fullPath: "/materials/boms";
      preLoaderRoute: typeof AuthenticatedMaterialsBomsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/execution/queue": {
      id: "/_authenticated/execution/queue";
      path: "/execution/queue";
      fullPath: "/execution/queue";
      preLoaderRoute: typeof AuthenticatedExecutionQueueRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dev/ui-kit": {
      id: "/_authenticated/dev/ui-kit";
      path: "/dev/ui-kit";
      fullPath: "/dev/ui-kit";
      preLoaderRoute: typeof AuthenticatedDevUiKitRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/admin/users": {
      id: "/_authenticated/admin/users";
      path: "/admin/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/work-orders_/$workOrderId/material-reservations": {
      id: "/_authenticated/work-orders_/$workOrderId/material-reservations";
      path: "/material-reservations";
      fullPath: "/work-orders/$workOrderId/material-reservations";
      preLoaderRoute: typeof AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRouteImport;
      parentRoute: typeof AuthenticatedWorkOrdersWorkOrderIdRoute;
    };
    "/_authenticated/quality/inspections_/$inspectionId": {
      id: "/_authenticated/quality/inspections_/$inspectionId";
      path: "/quality/inspections/$inspectionId";
      fullPath: "/quality/inspections/$inspectionId";
      preLoaderRoute: typeof AuthenticatedQualityInspectionsInspectionIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/quality/incidents_/$qualityIncidentId": {
      id: "/_authenticated/quality/incidents_/$qualityIncidentId";
      path: "/quality/incidents/$qualityIncidentId";
      fullPath: "/quality/incidents/$qualityIncidentId";
      preLoaderRoute: typeof AuthenticatedQualityIncidentsQualityIncidentIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/materials/lots_/$materialLotId": {
      id: "/_authenticated/materials/lots_/$materialLotId";
      path: "/materials/lots/$materialLotId";
      fullPath: "/materials/lots/$materialLotId";
      preLoaderRoute: typeof AuthenticatedMaterialsLotsMaterialLotIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/execution/lots_/$productionLotId/steps_/$processStepRevisionId": {
      id: "/_authenticated/execution/lots_/$productionLotId/steps_/$processStepRevisionId";
      path: "/execution/lots/$productionLotId/steps/$processStepRevisionId";
      fullPath: "/execution/lots/$productionLotId/steps/$processStepRevisionId";
      preLoaderRoute: typeof AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedWorkOrdersWorkOrderIdRouteChildren {
  AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute: typeof AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute;
}

const AuthenticatedWorkOrdersWorkOrderIdRouteChildren: AuthenticatedWorkOrdersWorkOrderIdRouteChildren =
  {
    AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute:
      AuthenticatedWorkOrdersWorkOrderIdMaterialReservationsRoute,
  };

const AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren =
  AuthenticatedWorkOrdersWorkOrderIdRoute._addFileChildren(
    AuthenticatedWorkOrdersWorkOrderIdRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedAuditEventsRoute: typeof AuthenticatedAuditEventsRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute;
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute;
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute;
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute;
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute;
  AuthenticatedDevUiKitRoute: typeof AuthenticatedDevUiKitRoute;
  AuthenticatedExecutionQueueRoute: typeof AuthenticatedExecutionQueueRoute;
  AuthenticatedMaterialsBomsRoute: typeof AuthenticatedMaterialsBomsRoute;
  AuthenticatedMaterialsLotsRoute: typeof AuthenticatedMaterialsLotsRoute;
  AuthenticatedQualityIncidentsRoute: typeof AuthenticatedQualityIncidentsRoute;
  AuthenticatedQualityInspectionsRoute: typeof AuthenticatedQualityInspectionsRoute;
  AuthenticatedTraceabilityTraceNodeIdRoute: typeof AuthenticatedTraceabilityTraceNodeIdRoute;
  AuthenticatedWorkOrdersWorkOrderIdRoute: typeof AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren;
  AuthenticatedWorkOrdersNewRoute: typeof AuthenticatedWorkOrdersNewRoute;
  AuthenticatedMaterialsLotsMaterialLotIdRoute: typeof AuthenticatedMaterialsLotsMaterialLotIdRoute;
  AuthenticatedQualityIncidentsQualityIncidentIdRoute: typeof AuthenticatedQualityIncidentsQualityIncidentIdRoute;
  AuthenticatedQualityInspectionsInspectionIdRoute: typeof AuthenticatedQualityInspectionsInspectionIdRoute;
  AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute: typeof AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditEventsRoute: AuthenticatedAuditEventsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDevUiKitRoute: AuthenticatedDevUiKitRoute,
  AuthenticatedExecutionQueueRoute: AuthenticatedExecutionQueueRoute,
  AuthenticatedMaterialsBomsRoute: AuthenticatedMaterialsBomsRoute,
  AuthenticatedMaterialsLotsRoute: AuthenticatedMaterialsLotsRoute,
  AuthenticatedQualityIncidentsRoute: AuthenticatedQualityIncidentsRoute,
  AuthenticatedQualityInspectionsRoute: AuthenticatedQualityInspectionsRoute,
  AuthenticatedTraceabilityTraceNodeIdRoute:
    AuthenticatedTraceabilityTraceNodeIdRoute,
  AuthenticatedWorkOrdersWorkOrderIdRoute:
    AuthenticatedWorkOrdersWorkOrderIdRouteWithChildren,
  AuthenticatedWorkOrdersNewRoute: AuthenticatedWorkOrdersNewRoute,
  AuthenticatedMaterialsLotsMaterialLotIdRoute:
    AuthenticatedMaterialsLotsMaterialLotIdRoute,
  AuthenticatedQualityIncidentsQualityIncidentIdRoute:
    AuthenticatedQualityIncidentsQualityIncidentIdRoute,
  AuthenticatedQualityInspectionsInspectionIdRoute:
    AuthenticatedQualityInspectionsInspectionIdRoute,
  AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute:
    AuthenticatedExecutionLotsProductionLotIdStepsProcessStepRevisionIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
