/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedWorkOrdersRouteImport } from "./routes/_authenticated.work-orders";
import { Route as AuthenticatedForbiddenRouteImport } from "./routes/_authenticated.forbidden";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated.dashboard";
import { Route as AuthenticatedAuditEventsRouteImport } from "./routes/_authenticated.audit-events";
import { Route as AuthenticatedWorkOrdersNewRouteImport } from "./routes/_authenticated.work-orders_.new";
import { Route as AuthenticatedWorkOrdersWorkOrderIdRouteImport } from "./routes/_authenticated.work-orders_.$workOrderId";
import { Route as AuthenticatedQualityInspectionsRouteImport } from "./routes/_authenticated.quality.inspections";
import { Route as AuthenticatedMaterialsLotsRouteImport } from "./routes/_authenticated.materials.lots";
import { Route as AuthenticatedExecutionQueueRouteImport } from "./routes/_authenticated.execution.queue";
import { Route as AuthenticatedDevUiKitRouteImport } from "./routes/_authenticated.dev.ui-kit";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: "/work-orders",
  path: "/work-orders",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAuditEventsRoute =
  AuthenticatedAuditEventsRouteImport.update({
    id: "/audit-events",
    path: "/audit-events",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedWorkOrdersNewRoute =
  AuthenticatedWorkOrdersNewRouteImport.update({
    id: "/work-orders_/new",
    path: "/work-orders/new",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedWorkOrdersWorkOrderIdRoute =
  AuthenticatedWorkOrdersWorkOrderIdRouteImport.update({
    id: "/work-orders_/$workOrderId",
    path: "/work-orders/$workOrderId",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedQualityInspectionsRoute =
  AuthenticatedQualityInspectionsRouteImport.update({
    id: "/quality/inspections",
    path: "/quality/inspections",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedMaterialsLotsRoute =
  AuthenticatedMaterialsLotsRouteImport.update({
    id: "/materials/lots",
    path: "/materials/lots",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedExecutionQueueRoute =
  AuthenticatedExecutionQueueRouteImport.update({
    id: "/execution/queue",
    path: "/execution/queue",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedDevUiKitRoute = AuthenticatedDevUiKitRouteImport.update({
  id: "/dev/ui-kit",
  path: "/dev/ui-kit",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/work-orders/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRoute;
  "/work-orders/new": typeof AuthenticatedWorkOrdersNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/forbidden": typeof AuthenticatedForbiddenRoute;
  "/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/work-orders/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRoute;
  "/work-orders/new": typeof AuthenticatedWorkOrdersNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/audit-events": typeof AuthenticatedAuditEventsRoute;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute;
  "/_authenticated/forbidden": typeof AuthenticatedForbiddenRoute;
  "/_authenticated/work-orders": typeof AuthenticatedWorkOrdersRoute;
  "/_authenticated/dev/ui-kit": typeof AuthenticatedDevUiKitRoute;
  "/_authenticated/execution/queue": typeof AuthenticatedExecutionQueueRoute;
  "/_authenticated/materials/lots": typeof AuthenticatedMaterialsLotsRoute;
  "/_authenticated/quality/inspections": typeof AuthenticatedQualityInspectionsRoute;
  "/_authenticated/work-orders_/$workOrderId": typeof AuthenticatedWorkOrdersWorkOrderIdRoute;
  "/_authenticated/work-orders_/new": typeof AuthenticatedWorkOrdersNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/audit-events"
    | "/dashboard"
    | "/forbidden"
    | "/work-orders"
    | "/dev/ui-kit"
    | "/execution/queue"
    | "/materials/lots"
    | "/quality/inspections"
    | "/work-orders/$workOrderId"
    | "/work-orders/new";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/audit-events"
    | "/dashboard"
    | "/forbidden"
    | "/work-orders"
    | "/dev/ui-kit"
    | "/execution/queue"
    | "/materials/lots"
    | "/quality/inspections"
    | "/work-orders/$workOrderId"
    | "/work-orders/new";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/audit-events"
    | "/_authenticated/dashboard"
    | "/_authenticated/forbidden"
    | "/_authenticated/work-orders"
    | "/_authenticated/dev/ui-kit"
    | "/_authenticated/execution/queue"
    | "/_authenticated/materials/lots"
    | "/_authenticated/quality/inspections"
    | "/_authenticated/work-orders_/$workOrderId"
    | "/_authenticated/work-orders_/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/work-orders": {
      id: "/_authenticated/work-orders";
      path: "/work-orders";
      fullPath: "/work-orders";
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/forbidden": {
      id: "/_authenticated/forbidden";
      path: "/forbidden";
      fullPath: "/forbidden";
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/audit-events": {
      id: "/_authenticated/audit-events";
      path: "/audit-events";
      fullPath: "/audit-events";
      preLoaderRoute: typeof AuthenticatedAuditEventsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/work-orders_/new": {
      id: "/_authenticated/work-orders_/new";
      path: "/work-orders/new";
      fullPath: "/work-orders/new";
      preLoaderRoute: typeof AuthenticatedWorkOrdersNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/work-orders_/$workOrderId": {
      id: "/_authenticated/work-orders_/$workOrderId";
      path: "/work-orders/$workOrderId";
      fullPath: "/work-orders/$workOrderId";
      preLoaderRoute: typeof AuthenticatedWorkOrdersWorkOrderIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/quality/inspections": {
      id: "/_authenticated/quality/inspections";
      path: "/quality/inspections";
      fullPath: "/quality/inspections";
      preLoaderRoute: typeof AuthenticatedQualityInspectionsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/materials/lots": {
      id: "/_authenticated/materials/lots";
      path: "/materials/lots";
      fullPath: "/materials/lots";
      preLoaderRoute: typeof AuthenticatedMaterialsLotsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/execution/queue": {
      id: "/_authenticated/execution/queue";
      path: "/execution/queue";
      fullPath: "/execution/queue";
      preLoaderRoute: typeof AuthenticatedExecutionQueueRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/dev/ui-kit": {
      id: "/_authenticated/dev/ui-kit";
      path: "/dev/ui-kit";
      fullPath: "/dev/ui-kit";
      preLoaderRoute: typeof AuthenticatedDevUiKitRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditEventsRoute: typeof AuthenticatedAuditEventsRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute;
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute;
  AuthenticatedDevUiKitRoute: typeof AuthenticatedDevUiKitRoute;
  AuthenticatedExecutionQueueRoute: typeof AuthenticatedExecutionQueueRoute;
  AuthenticatedMaterialsLotsRoute: typeof AuthenticatedMaterialsLotsRoute;
  AuthenticatedQualityInspectionsRoute: typeof AuthenticatedQualityInspectionsRoute;
  AuthenticatedWorkOrdersWorkOrderIdRoute: typeof AuthenticatedWorkOrdersWorkOrderIdRoute;
  AuthenticatedWorkOrdersNewRoute: typeof AuthenticatedWorkOrdersNewRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditEventsRoute: AuthenticatedAuditEventsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedDevUiKitRoute: AuthenticatedDevUiKitRoute,
  AuthenticatedExecutionQueueRoute: AuthenticatedExecutionQueueRoute,
  AuthenticatedMaterialsLotsRoute: AuthenticatedMaterialsLotsRoute,
  AuthenticatedQualityInspectionsRoute: AuthenticatedQualityInspectionsRoute,
  AuthenticatedWorkOrdersWorkOrderIdRoute:
    AuthenticatedWorkOrdersWorkOrderIdRoute,
  AuthenticatedWorkOrdersNewRoute: AuthenticatedWorkOrdersNewRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
